# Generated by Django 5.0.1 on 2024-10-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
