# Generated by Django 5.0.1 on 2024-10-29 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_proessor_classroom_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom'),
        ),
    ]
