# Generated by Django 5.0.1 on 2024-10-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_classroom_activity_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='identification',
            field=models.CharField(max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
