# Generated by Django 5.0.1 on 2024-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classroom_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom_activity',
            name='status',
        ),
        migrations.AddField(
            model_name='classroom_activity',
            name='endsAt',
            field=models.DateTimeField(blank=True, default='2000-01-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom_activity',
            name='startsAt',
            field=models.DateTimeField(blank=True, default='2000-01-10'),
            preserve_default=False,
        ),
    ]
