# Generated by Django 5.0.1 on 2024-11-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_classroom_activity_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom_activity',
            old_name='endsAt',
            new_name='ends_at',
        ),
        migrations.RenameField(
            model_name='classroom_activity',
            old_name='startsAt',
            new_name='starts_at',
        ),
    ]
