# Generated by Django 5.0.1 on 2024-11-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_endsat_classroom_activity_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activity',
            name='score',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
