# Generated by Django 5.0.1 on 2024-11-13 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_activity_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate',
            old_name='function_string',
            new_name='circuit_json',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='outputs',
        ),
    ]
