# Generated by Django 5.0.1 on 2024-11-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_activity_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='solution_url',
            new_name='solution_image',
        ),
    ]
