# Generated by Django 5.0.1 on 2024-11-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_function_string_gate_circuit_json_and_more'),
        ('api', '0013_rename_solution_url_activity_solution_image'),
    ]

    operations = [
    ]
