# Generated by Django 5.0.1 on 2024-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20241113_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='testbench',
            field=models.TextField(blank=True),
        ),
    ]
