const Settings = {
    CANVAS_BACKGROUND_COLOR: "#282828",
    BINDING_BOX_COLOR: "#3D3D3D",
    TOOLBOX_COLOR: "#0C0C0C",
    SAVED_GATE_COLOR: "#262626",
    IO_CIRCLE_RADIUS: 20,
    COMPONENT_IO_OFF_COLOR: "#1C2027",
    COMPONENT_IO_ON_COLOR: "#348c20",
    COMPONENT_IO_CIRCLE_RADIUS: 10,
    WIRE_COLOR: "#00F",
    WIRE_WIDTH: 3,
    WIRE_DOT_RADIUS: 3,
};

export default Settings;
